### ISSUE TITLE
Number of nodes found: 0

### ISSUE THREAD

**Issue by martinglass** [pulquero/RotorHazard#103]
There's an issue detecting I2C nodes with the latest BH (5-Feb-2022), which wasn't there previously (namely, BH version dated 20-Jan-2022)

I'm using an Arduino/Pi setup using I2C, which was working fine with BH last month. I picked it up again to test the new version of BH, but the Pi Server wouldn't detect the Nano Node Managers.

The log generated this ...
_**rh.interface.nodes.i2c_node [INFO] Searching for I2C nodes...
rh.interface.Node [WARNING] Retry ([Errno 121] Remote I/O error) limit reached in read_command: addr=i2c:1/0x08 cmd=0x01 size=1 retry=2
_main_ [INFO] Number of nodes found: 0**_

**Comment by pulquero** [comment]
Works for me, looks like you may have a hardware issue.

**Comment by martinglass** [comment]
I've reloaded the firmware and it's all working okay now. Glad that's sorted.
