### ISSUE TITLE
import errors

### ISSUE THREAD

**Issue by martinglass** [pulquero/RotorHazard#12]
Files: server.py, Database.py, Results.py, RHData.py, ClusterNodeSet.py, PageCache.py, led_event_manager.py, 

I'm getting loads of import errors, relating to lines such as these and more...
  from . import log
  from . import Config, Database, Results, Language, RHData, RHUtils
  from .RHUtils import catchLogExceptionsWrapper
  from interface.Plugins import Plugins, search_modules

Also, these imports fail...
import helpers as helper_pkg
import sensors as sensor_pkg
import leds as led_pkg

**Comment by pulquero** [comment]
Are you in /src and running python3 -m server.server (see updated readme)? Change was unavoidable to fix alot of issues with project organisation.

**Comment by martinglass** [comment]
Oops. Didn’t see the readme update. I was running in src/server as normal.
