### ISSUE TITLE
Beeper on STM32 boards has stopped working

### ISSUE THREAD

**Issue by Aaronsss** [pulquero/RotorHazard#120]
STM32 boards feature a beeper. The old bahaviour is that it would beep during start up once when the STM32 was booted and then again when the server had booted up.

The beeper no longer sounds (I think this change happened a little while ago) but uncertain if this was intentional or not

**Comment by pulquero** [comment]
This a beeper connected to pins on the stm32?

**Comment by martinglass** [comment]
https://www.lego.com/en-gb/product/hogwarts-magical-trunk-76399

Pin PA8 (A8)

![image](https://user-images.githubusercontent.com/41255030/192891881-a684cb88-2665-4b29-8f61-ef0d0f194c64.jpeg)
