### ISSUE TITLE
Testing the Tests

### ISSUE THREAD

**Issue by martinglass** [pulquero/RotorHazard#40]
Testing the tests:

**In this instance, test_sensors. Here's what happened....**

**~/RotorHazard/src $ python -m tests.test_sensors**

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/RotorHazard/src/tests/test_sensors.py", line 5, in <module>
    import fake_rpi
ModuleNotFoundError: No module named 'fake_rpi'

**Comment by pulquero** [comment]
Non-pi requirements are needed for tests:
python3 -m pip install -r reqsNonPi.txt

**Comment by martinglass** [comment]
I've updated my comments.

Can I safely install the non-pi requirements and run the tests on the pi?

**Comment by martinglass** [comment]
Test_Interface: 

Plugin interface.i2c_node not loaded (not supported - required arguments are not available)
	discover() missing 1 required positional argument: 'i2c_helper'

Don't know whether this error report significant. The tests ended with **"OK"**

**Comment by martinglass** [comment]
**In this instance, test_server. Here's what I found**
**~/RotorHazard/src $ python -m tests.test_sensors**

The test created a number of things in the database, such as new (test) pilots, new race formats and more. It would be best not to alter the original database (if one exists), eg rename the existing one before running the test code, then deleting the database created by the test code and restoring the original database back into place.

This is especially problematic, because all but one of the newly-created Test Pilots were locked (there was no "x" icon by their Team to delete them, in the *Pilots* section).

Also, the phonetic for the Test Pilot is typed *Teeest* for some reason

**Comment by pulquero** [comment]
> Plugin interface.i2c_node not loaded (not supported - required arguments are not available)
> discover() missing 1 required positional argument: 'i2c_helper'
> 
> Don't know whether this error report significant. The tests ended with **"OK"**

The error here explains why I2C is not available (which is expected for the test).

> Also, the phonetic for the Test Pilot is typed Teeest for some reason

Delibrate spelling to emphasize phonetics.
