### ISSUE TITLE
Bluetooth Control

### ISSUE THREAD

**Issue by martinglass** [pulquero/RotorHazard#44]
Can this sort of python wrapper for bluetoothctl be useful in the RH-Audio code?

I'm thinking that a BT discovery code could identify if BT devices are available for Audio to supplement the Mac addresss lines in the new Audio section in the config.json file.

Anyway, just a thought on how this useful Audio branch could be developed further.

https://gist.github.com/egorf/66d88056a9d703928f93
forked for Python 3.6.8 on RPi: https://gist.github.com/castis/0b7a162995d0b465ba9c84728e60ec01

**Comment by pulquero** [comment]
Potentially, but I think it is better to try to leave audio handling to the operating system. RH should just output audio then you are free to configure the system to output it where you like, be it over bluetooth on an audio stream over the internet.

If configuring BT on the Pi proves troublesome, then I'll consider a standalone/companion python program to configure BT audio.

**Comment by martinglass** [comment]
I like your thinking - but it kind of conflicts with having an Audio section in the config.json file, don't you agree?

**Comment by pulquero** [comment]
The audio section is there to configure the "how", how should the audio be generated. "Where" is left to the o/s.
