### ISSUE TITLE
BQE Race Formats

### ISSUE THREAD

**Issue by martinglass** [pulquero/RotorHazard#55]
Can RotorHazard do these Race Formats? Excuse this if it's been asked before. 

1) At least in U.K. (and probably elsewhere too) Racing Pilots are used to 2 minute races with 30 seconds extension to finish their last lap. 
2) Nowadays, the number of laps after the first round (or first few rounds) are capped. I think this is already a feature of RH though. 
3) Qualifying rounds feed into Finals, where pilots are seeded according to their performance in their best X out of N rounds of the Qualifiers (eg best 4 out of 7). Can RH automatically generate Final Heats based on criteria (eg most laps & fastest, or fastest 3 consecutive)?

**Comment by pulquero** [comment]
BQE style mains can now be generated, so I think that is everything.
